### ISSUE TITLE
agregar secciones restantes

### ISSUE THREAD

**Issue by yovany-dev** [WizardRRR/maximorphs-landing-page-community#5]
Hola, quisiera trabajar el las 4 secciones restantes para la página, las secciones que se trabajaran son:

- Elige tu maximorphs
- Comunidad y Donación
- Preguntas y respuestas (iframe youtube)
- Footer (enlaces a redes sociales)

**Comment by WizardRRR** [comment]
dale cada commit con cada sección

**Comment by WizardRRR** [comment]
PR #6  by @yovany-dev solved
